# Generated by Django 4.2.2 on 2023-09-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0004_remove_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='11', upload_to='product_images/'),
        ),
    ]
