# Generated by Django 4.2.2 on 2023-09-05 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0005_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='USERAPP.subcategory'),
        ),
    ]
